spring.application.name=UrlShortener
spring.datasource.url=jdbc:sqlite:src/main/resources/test.db
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always
spring.jpa.hibernate.ddl = create
spring.jpa.hibernate.ddl-auto=update